---
- hosts: 18.222.186.248
  become: yes
  tasks: 
   - name: install git on redhatnode
     yum: 
      name: git
      state: present

   - name: install webserver on Redhatnote
     yum: 
      name: httpd
      state: present

   - name: start webserver on redhatnode
     yum: 
      name: httpd
      state: present
