--- 
- hosts: webservers
  become: yes
  tasks: 
   - name: I wanto to execute linux commands
     command: hostname -f 
     register: myresult

   - name: I want to display matter stored in myresult variable 
     debug:
      msg: "{{myresult}}"

   - name: I wanto to install git if no error
     apt:
      name: git
      state: present
    when: myresult.stderr == ""

