---
- hosts: webservers
  become: yes
  tasks: 
   - name: I want to install java8 on Ubuntu
     apt:
      name: openjdk-8-jre
      state: present
     when: ansible_os_family== "Debian" 

   - name: I want to install java8 on RedHat
     yum:
      name: java-1.8.0-openjdk
      state: present
     when: ansible_os_family== "RedHat" 
