---
- hosts: webservers
  become: yes
  tasks: 
   - name: I want to install java8 on Ubuntu
     apt:
      name: "{{javapackonubuntu}}"
      state: present
     when: ansible_os_family== "Debian" 

   - name: I want to install java8 on RedHat
     yum:
      name: "{{javapackonredhat}}"
      state: present
     when: ansible_os_family== "RedHat" 
