---
- hosts: all
  become: yes
  tasks:
  - name: Install webserver on Ubuntu
    apt:
     name: apache2
     state: present
    when: ansible_os_family== "Debian"
  - name: Start webserver on Ubuntu
    service: 
     name: apache2
     state: started 
    when: ansible_os_family== "Debian" 
