---
- hosts: all 
  become: yes

    tasks:
    - name: installing webserver
      apt:
       name: apache2
       state: present

    - name: starting webserver
      service: 
       name: apache2
       status: started
        



